### ISSUE TITLE
Using incline key from OSM?

### ISSUE THREAD

**Issue by rnorris** [nautoguide/gradient_markers#1]
I don't think I've noticed any mention of generating markers directly from incline keys in OSM itself.

http://wiki.openstreetmap.org/wiki/Key:incline

For several years whilst cycling around the UK I add signed inclines when I come across them.

Thus you could use these values - either directly - or may be as a conflation conformation / confidence against DEM or GPX derived gradients.

Of course highway incline tags won't have complete coverage (and many hills which have chevrons on OS maps don't always have incline signs) and only those which have incline=number% value are usable.

NB.
A couple of years ago I played with a program using STRM and OSM that included trying to work out gradients. 
It was a fairly simple program in C++ with (lib)Osmium using the raw data directly (rather than using PostgisSQL or similar)- I've haven't gotten around to releasing it publicly as IIRC my method of trying to find the _steepest_ gradients suffered from edge problems in the DEM data leading to returning gradients around 50%.
I never got around to improving it for general road gradients either, but at least I could confirm that the highest pub in England is the Tan Hill Inn :)

**Comment by citizenfish** [comment]
I have looked at these, coverage is sparse and my aim is to add to them rather than use them. As you say they would make a good confidence check.

I've honed the process a bit more and hope to kick off a full UK generation exercise this month.  Hopefully very soon we will be able to compare algorithms as I think my contour approach helps smooth the DEM edge problems.

Thanks
Dave
